EventBrite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name='home'),
    re_path(r'^test/$', views.TestPage.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    re_path(r'^appreciate/$', views.AppreciationPage.as_view(), name='appreciate'),
    re_path(r'^find/$', views.FindPage.as_view(), name = 'find'),
    re_path(r'^help/$', views.HelpPage.as_view(), name = 'help'),
    re_path(r'^thanksreg/$', views.ThanksRegistration.as_view(), name='thanksreg'),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts', include('django.contrib.auth.urls')),
    re_path(r'CreateEvent/', include("CreateEvent.urls", namespace="CreateEvent")),
    re_path(r'EventFinder/', include("EventFinder.urls", namespace="EventFinder"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EventFinder/urls.py
# EventFinder urls.py file
from django.urls import re_path, path
from . import views


app_name = 'EventFinder'

urlpatterns = [
    re_path(r'^finder$', views.EventFinder.as_view(), name='finder'),
    path('events/<int:event_id>/register/', views.RegistrationPage.as_view(), name='registration'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='detail'),
]

accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns=[
    re_path(r'^login$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^logout$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
    re_path('reset_password/',
            auth_views.PasswordResetView.as_view(template_name ="accounts/password_reset.html"),
            name='reset_password'),
    re_path('reset_password_sent/',
            auth_views.PasswordResetDoneView.as_view(template_name ="accounts/password_reset_sent.html"),
            name = 'password_reset_done'),
    re_path('reset/<uidb64/<token>/>',
            auth_views.PasswordResetConfirmView.as_view(template_name ="accounts/password_reset_form.html"),
            name = 'password_reset_confirm'),
    re_path('reset_password_complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name ="accounts/password_reset_done.html"),
            name='password_reset_complete')
]

EventFinder/models.py
from django.db import models
from datetime import datetime

from django.shortcuts import get_object_or_404
from django.utils.text import slugify
# Create your models here.
from CreateEvent.models import BasicInfo


class Register(models.Model):
    first_name = models.CharField(max_length=255, blank=False)
    last_name = models.CharField(max_length=255, blank=False)
    phone_number = models.IntegerField(unique=True)
    email_address = models.EmailField(unique=True)
    event = models.ForeignKey(BasicInfo, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.first_name)
        super().save(*args, **kwargs)

EventFinder/forms.py
from django import forms
from . import models


class registerForm(forms.ModelForm):
    class Meta:
        model = models.register
        fields = ("first_name", "last_name", "phone_number", "email_address")
        # exclude = ("event")

EventFinder/views.py
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import generic
from django.core.mail import send_mail
from django.urls import reverse_lazy
from CreateEvent.models import BasicInfo
from EventFinder.models import Register
# from braces.views import SelectRelatedMixin

# Create your views here.

class EventFinder(generic.ListView):
    model = BasicInfo
    paginate_by = 10 #if pagination is desired

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context
    template_name = 'eventfinder/finder.html'

class EventDetail(generic.DetailView):
    model = BasicInfo

    # queryset = models.EventFinder.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    # def get_object(self, query_set):
    #     event = get_object_or_404(EventFinder, pk=self.kwargs['pk'])
    #     return event

    template_name = 'eventfinder/eventdetail.html'

class RegistrationPage(generic.CreateView):
    fields = ("first_name","last_name", "phone_number","email_address")
    model = Register

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['event_id'] = self.kwargs['event_id']
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        # self.object.user = self.request.user
        self.object.event = get_object_or_404(BasicInfo, pk=self.kwargs['event_id'])
        self.object.save()
        self.sendmail(form)
        return super().form_valid(form)
    success_url =reverse_lazy('thanksreg')
    template_name ='eventfinder/register.html'
    def sendmail(self, form):
        # template = render_to_string('eventfinder/email_template.html', {'name': request.user.profile.first_name})
        send_mail(
            'subject here',
            'Hey! Thanks for registering for this event. Hope to see you there!',
            'woleoyediran25@gmail.com',
            ['woleoyediran@gmail.com'],
            fail_silently=False,
        )

templates/eventfinder/Finder_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="https://kit.fontawesome.com/df3dc7351e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'EventBrite/CSS/master.css'%}">
    <style>
       *{
  margin: 0;
  overflow: hidden;
  color: black;
}
.tommy{
  position: relative;
  display: in-block;
}
.tommy:hover.gentle{
  display:block;
  right: 0;
}
.gentle{
  display:none;
  position:absolute;
}
.gentle a{
  text-decoration: none;
  color: green;
}
.gentle a:hover{
  color: red;
}
.clock{
  height: 200px;
}
.main{
  display: flex;
}
.dam{
  display:flex;
  flex-direction:column;
  justify-content: space-between;
}
.prom{
  width:80px;
}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-left">
          <a class="navbar-brand mynav owen text-left " href="{% url 'home' %}">BLACKBRIAR</a>
        </div>
        <div class="navbar-nav align-items-right">
            <div class="tommy">
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Organise</a>
              <div class="gentle bg-light">
                <a class="nav-item nav-link" href="#">Why EventBrite</a>
                <a class="nav-item nav-link" href="#">Pricing</a>
                <a class="nav-item nav-link" href="#">Resources</a>
              </div>
            </div>
            <div class="tommy">
              <a class="nav-item nav-link unique" href="#">Help</a>
              <div class="gentle bg-light">
                <a class="nav-item nav-link" href="{% url 'find' %}">Find your ticket</a>
                <a class="nav-item nav-link" href="#">Contact an Event Organizer</a>
                <a class="nav-item nav-link" href="{% url 'help' %}">Visit the Help Center</a>
              </div>
            </div>
<!--            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log In</a>-->
<!--            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>-->
        </div>
      </div>
    </nav>

    <div class="mycontent">
      {% block content%}
      {% endblock %}
    </div>
    <canvas id="canvas"></canvas>
<!--    <script src="{% static "EventBrite/JS/master.js"%}" type="text/javascript" ></script>-->

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/eventfinder/email_template.html
Hey {{name}}!
Just wanted to thank you for registering to attend this event

Here is your event ticket identification {{id}}

Looking forward to seeing you there!  :)

BlackBriar Events!

templates/eventfinder/eventdetail.html
{% extends 'eventfinder/Finder_base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="col-md-8">
  <h2>Event Name:{{object.name}}</h2>
  <br>
  <h2>Organiser:{{object.organizer}}</h2>
  <br>
  <h2>Date:{{object.date}}</h2>
  <br>
  <h2>Venue: {{object.venue}}</h2>
  <br>
  <h2>Details on Event: {{object.details}}</h2>
  <br>
  <h2> <img style="height:300px;" src="{{object.image.url}}"> </h2>
  <br>
</div>

<a class="button"  style="background-color: #1c87c9;
        border: none;
        border-radius: 50px;
        color: black;
        padding: 20px 34px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 20px;
        margin: 4px 2px;
        cursor: pointer;" href="{% url 'EventFinder:registration' event_id=object.id %}">Register</a>
{% endblock%}

templates/eventfinder/finder.html
{% extends 'eventfinder/Finder_base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="col-md-8">
  <h4>Things to do in</h4>
  <h2>Lagos?</h2>
  <h1>Events</h1>
</div>
<div style="display:flex; flex-wrap: wrap; width:1500px; align-items:center;" data-spy="scroll">
{% for event in object_list %}
    <div class="card" style="width: 200px; margin:20px">
      <img class="card-img-top" src="{{ event.image.url }}">
      <div class="card-body">
        <h5 class="card-title">{{event.name }}</h5>
        <p class="card-text">{{ event.date|date }}.</p>
        <a href="{% url 'EventFinder:detail' pk=event.id  %}">Register</a>
        <p class="card-text">{{ event.venue }}</p>
      </div>
    </div>
<!--    <li><img style="height:50px;" src="{{ event.image.url }}"><a href="{% url 'EventFinder:detail' pk=event.id  %}">{{ event.name }} - {{ event.date|date }} - {{ event.venue }}</a></li>-->
{% endfor %}
</div>
{% endblock%}

templates/eventfinder/register.html
{% extends 'eventfinder/Finder_base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div>
  <h2>Register Here:</h2>
  <p>Please input all your information correctly to register for the event you would like to attend</p>
  <form action="{% url 'EventFinder:registration' event_id=event_id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Save" class="btn btn-primary btn-large">
  </form>
</div>

{% endblock %}