CreateEvent/urls.py
# CreateEvent urls.py file
from django.urls import re_path
from . import views

app_name = 'CreateEvent'

urlpatterns=[
    re_path(r'^new$', views.CreateEvent.as_view(), name='create'),
    re_path(r'^ticket$', views.AddTickets.as_view(), name='addticket'),
    re_path(r'^dashboard$', views.Dashboard.as_view(), name='dashboard')
]

EventBrite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.HomePage.as_view(), name='home'),
    re_path(r'^test/$', views.TestPage.as_view(), name='test'),
    re_path(r'^thanks/$', views.ThanksPage.as_view(), name='thanks'),
    re_path(r'^appreciate/$', views.AppreciationPage.as_view(), name='appreciate'),
    re_path(r'^find/$', views.FindPage.as_view(), name = 'find'),
    re_path(r'^help/$', views.HelpPage.as_view(), name = 'help'),
    re_path(r'^thanksreg/$', views.ThanksRegistration.as_view(), name='thanksreg'),
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^accounts', include('django.contrib.auth.urls')),
    re_path(r'CreateEvent/', include("CreateEvent.urls", namespace="CreateEvent")),
    re_path(r'EventFinder/', include("EventFinder.urls", namespace="EventFinder"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EventFinder/urls.py
# EventFinder urls.py file
from django.urls import re_path, path
from . import views


app_name = 'EventFinder'

urlpatterns = [
    re_path(r'^finder$', views.EventFinder.as_view(), name='finder'),
    path('events/<int:event_id>/register/', views.RegistrationPage.as_view(), name='registration'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='detail'),
]

accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns=[
    re_path(r'^login$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^logout$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'signup/$', views.SignUp.as_view(), name='signup'),
    re_path('reset_password/',
            auth_views.PasswordResetView.as_view(template_name ="accounts/password_reset.html"),
            name='reset_password'),
    re_path('reset_password_sent/',
            auth_views.PasswordResetDoneView.as_view(template_name ="accounts/password_reset_sent.html"),
            name = 'password_reset_done'),
    re_path('reset/<uidb64/<token>/>',
            auth_views.PasswordResetConfirmView.as_view(template_name ="accounts/password_reset_form.html"),
            name = 'password_reset_confirm'),
    re_path('reset_password_complete/',
            auth_views.PasswordResetCompleteView.as_view(template_name ="accounts/password_reset_done.html"),
            name='password_reset_complete')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>EventBrite</title>
    <script src="https://kit.fontawesome.com/df3dc7351e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--    <link rel="stylesheet" type="text/css" href="{% static '/EventBrite/CSS/master.css'%}">-->
    <style>
      *{
  margin: 0;
  overflow: hidden;
  color: black;
}
.tommy{
  position: relative;
  display: in-block;
}
.tommy:hover.gentle{
  display:block;
  right: 0;
}
.gentle{
  display:none;
  position:absolute;
}
.gentle a{
  text-decoration: none;
  color: green;
}
.gentle a:hover{
  color: red;
}
.clock{
  height: 200px;
}
.main{
  display: flex;
}
.dam{
  display:flex;
  flex-direction:column;
  justify-content: space-between;
}
.prom{
  width:80px;
}
img{
  width:100%;
  height:550px;
  object-fit:cover;
}
.terry{
  background:violet;
}
.owen{
  color:green;
}
.button {
        background-color: violet;
        border: none;
        border-radius: 20px;
        color: white;
        padding: 15px 30px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 20px;
        margin: 4px 2px;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light terry" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-left">
          <a class="navbar-brand mynav owen text-left " href="{% url 'home' %}">BLACKBRIAR</a>
        </div>
        <div class="navbar-nav align-items-right">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#">Organise</a>
            <a class="nav-item nav-link" href="{% url 'help' %}">Help</a>
            <a class="nav-item nav-link fa fa-plus" href="{% url 'CreateEvent:create' %}">Create an Event</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
            <div class="tommy btn-group">
              <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Organise</button>
              <div class="gentle bg-light dropdown-menu">
                <a class="nav-item nav-link dropdown-item" href="#">Why EventBrite</a>
                <a class="nav-item nav-link dropdown-item" href="#">Pricing</a>
                <a class="nav-item nav-link dropdown-item" href="#">Resources</a>
              </div>
            </div>
            <div class="tommy">
              <a class="nav-item nav-link unique" href="#">Help</a>
              <div class="gentle bg-light">
                <a class="nav-item nav-link" href="{% url 'find' %}">Find your ticket</a>
                <a class="nav-item nav-link" href="#">Contact an Event Organizer</a>
                <a class="nav-item nav-link" href="{% url 'help' %}">Visit the Help Center</a>
              </div>
            </div>

            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Create an Event</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log In</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            <div>Forgot password?<a href="{% url 'accounts:reset_password' %}">Reset Password</a></div>
          {% endif %}
        </div>
      </div>
    </nav>
    <div style="max-width:auto">
      <img src="static/IMAGES/event.jpg" class="jerry">
    </div>

    <div class="mycontent">
      {% block content%}
      {% endblock %}
    </div>
    <div>
      <a class="nav-item nav-link button" href="{% url 'EventFinder:finder' %}">Find your next event</a>
    </div>
    <canvas id="canvas"></canvas>

    <script src="{% static "EventBrite/JS/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/createappreciation.html
{% extends 'jerry.html' %}

{% block content %}
<h2>Thanks For Creating an event, Hope To See You Soon!</h2>




<h6>You can search for events here: <a href = "{% url 'EventFinder:finder' %}">Event Finder</a></h6>
{% endblock %}

templates/findticket.html
{% extends 'jerry.html' %}

{% block content %}
<div class="clock">
  <img src="EventBrite/static/IMAGES/bartus.jpg" alt="">
</div>



{% endblock %}

templates/help.html
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Help-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->



<!--<div class="dropdown show">-->
<!--  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--    Dropdown link-->
<!--  </a>-->

<!--  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">-->
<!--    <a class="dropdown-item" href="#">Action</a>-->
<!--    <a class="dropdown-item" href="#">Another action</a>-->
<!--    <a class="dropdown-item" href="#">Something else here</a>-->
<!--  </div>-->
<!--</div>-->
{% extends 'jerry.html' %}

{% block content %}
<br>
<h2>Why Should you use EventBrite :</h2>
<br>

<p><b><i>
  Lorem Ipsum is simply dummy text of the printing and typesetting industry.
      Lorem Ipsum has been the industry's standard dummy text ever since the 1500s
      when an unknown printer took a galley of type and scrambled it to make a type
      specimen book. It has survived not only five centuries, but also the leap into
      electronic typesetting, remaining essentially unchanged. It was popularised in
      the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
      and more recently with desktop publishing software like Aldus PageMaker
      including versions of Lorem Ipsum. It is a long established fact that a
      reader will be distracted by the readable content of a page when looking
      at its layout. The point of using Lorem Ipsum is that it has a more-or-less
      normal distribution of letters, as opposed to using 'Content here, content here',
      making it look like readable English. Many desktop publishing packages and
      web page editors now use Lorem Ipsum as their default model text, and a
      search for 'lorem ipsum' will uncover many web sites still in their infancy.
</i></b></p>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1> Welcome To BLACKBRIAR</h1>


{% endblock %}

templates/jerry.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>EventBrite</title>
    <script src="https://kit.fontawesome.com/df3dc7351e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--    <link rel="stylesheet" type="text/css" href="{% static '/EventBrite/CSS/master.css'%}">-->
    <style>
       *{
  margin: 0;
  overflow: hidden;
  color: black;
}
.tommy{
  position: relative;
  display: in-block;
}
.tommy:hover.gentle{
  display:block;
  right: 0;
}
.gentle{
  display:none;
  position:absolute;
}
.gentle a{
  text-decoration: none;
  color: green;
}
.gentle a:hover{
  color: red;
}
.clock{
  height: 200px;
}
.main{
  display: flex;
}
.dam{
  display:flex;
  flex-direction:column;
  justify-content: space-between;
}
.prom{
  width:80px;
}
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light terry" role="navigation" id="navbar" style="position:sticky; top:0; margin-bottom:10px;">
      <div class="container">
        <div class="navbar-nav align-items-left">
          <a class="navbar-brand mynav owen text-left " href="{% url 'home' %}">BLACKBRIAR</a>
        </div>
        <div class="navbar-nav align-items-right">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#">Organise</a>
            <a class="nav-item nav-link" href="{% url 'help' %}">Help</a>
            <a class="nav-item nav-link fa fa-plus" href="{% url 'CreateEvent:create' %}">Create an Event</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
          {% else %}
            <div class="tommy">
              <a class="nav-item nav-link" href="#">Organise</a>
              <div class="gentle bg-light">
                <a class="nav-item nav-link" href="#">Why EventBrite</a>
                <a class="nav-item nav-link" href="#">Pricing</a>
                <a class="nav-item nav-link" href="#">Resources</a>
              </div>
            </div>
            <div class="tommy">
              <a class="nav-item nav-link unique" href="#">Help</a>
              <div class="gentle bg-light">
                <a class="nav-item nav-link" href="{% url 'find' %}">Find your ticket</a>
                <a class="nav-item nav-link" href="#">Contact an Event Organizer</a>
                <a class="nav-item nav-link" href="{% url 'help' %}">Visit the Help Center</a>
              </div>
            </div>

            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Create an Event</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log In</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            <div>Forgot password?<a href="{% url 'accounts:reset_password' %}">Reset Password</a></div>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="mycontent" data-spy="scroll" data-target=".nav">
      {% block content%}
      {% endblock %}
    </div>
  </body>
</html>

templates/test.html
{% extends 'jerry.html' %}

{% block content %}
<h2>You are now logged in!</h2>
{% endblock %}

templates/thanks.html
{% extends 'jerry.html' %}

{% block content %}
<h2>Thanks For Visiting, Hope To See You Soon!</h2>
{% endblock %}

templates/thanksreg.html
{% extends 'jerry.html' %}

{% block content %}
<h2>Thanks For Registering. Hope to see you at the event, {{user.username}}</h2>
{% endblock %}